server:
  port: 8081

spring:
  profiles:
    active: dev

  # PostgreSQL / Timescale
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      connection-init-sql: "SET search_path TO alert, public"


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

  # GraphQL endpoint
  graphql:
    path: /graphql
    websocket:
      path: /graphql

  # Flyway
  flyway:
    schemas: alert
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: alert
    open-in-view: false

alert:
  kafka:
    group-id: alert-service
    topic-raw: iot.raw
  telegram:
    token: ${TG_BOT_TOKEN}
    chat-id: ${TG_CHAT_ID}
