spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: alert-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

alert:
  thresholds:
    # field -> max value
    temperature: 30
    humidity: 80
    pm25: 50
    air_quality: 150
  email-to: ${ALERT_EMAIL:your@mail.com}
