package com.example.iot.alert.domain.mapper;

import com.example.iot.alert.domain.dto.AlertLogDto;
import com.example.iot.alert.domain.model.AlertLogEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface AlertLogMapper {

    AlertLogDto toDto(AlertLogEntity entity);

    List<AlertLogDto> toDto(List<AlertLogEntity> list);

    @Mapping(target = "id", ignore = true)           // generated by DB
    AlertLogEntity toEntity(AlertLogDto dto);
}
