name: build-and-push

on:
  push:
    branches: [ master ]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ingest   # ghcr.io/<user>/<repo>-ingest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write          # so we can push to ghcr
    steps:
      # 1) checkout
      - uses: actions/checkout@v4

      # 2) set up JDK 21
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 3) Build + unit-tests
      - name: Maven package
        run: |
          cd ingest-service
          ./mvnw -B verify spring-boot:repackage

      # 4) Build Docker image (multi-stage Dockerfile lives in ingest-service/)
      - name: Build & tag Docker image
        run: |
          docker build -t $REGISTRY/${IMAGE_NAME}:sha-${GITHUB_SHA::8} ingest-service
          docker tag  $REGISTRY/${IMAGE_NAME}:sha-${GITHUB_SHA::8} \
                      $REGISTRY/${IMAGE_NAME}:latest

      # 5) Login to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6) Push both tags
      - name: Push
        run: |
          docker push $REGISTRY/${IMAGE_NAME}:sha-${GITHUB_SHA::8}
          docker push $REGISTRY/${IMAGE_NAME}:latest
