name: build-and-push

on:
  push:
    branches: [ master ]
  pull_request:

env:
  REGISTRY: ghcr.io               # target registry

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write             # required to push to GHCR
    steps:
      # 1) checkout
      - uses: actions/checkout@v4

      # 2) set up JDK 21
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      # 3) compile & unit-tests
      - name: Maven package
        run: |
          cd ingest-service
          ./mvnw -B verify spring-boot:repackage

      # 4) compute lower-case image name
      - name: Normalize image name
        id: vars
        run: |
          IMAGE_NAME_LC=$(echo "${{ github.repository }}-ingest" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME_LC" >> $GITHUB_ENV
          echo "Using image name: $IMAGE_NAME_LC"

      # 5) build & tag Docker image
      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:sha-${GITHUB_SHA::8} ingest-service
          docker tag  $REGISTRY/$IMAGE_NAME:sha-${GITHUB_SHA::8} \
                      $REGISTRY/$IMAGE_NAME:latest

      # 6) login to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7) push tags
      - name: Push image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:sha-${GITHUB_SHA::8}
          docker push $REGISTRY/$IMAGE_NAME:latest
